from __future__ import annotations

MAX_TURNS_FOR_EVAL = 40
MAX_TEXT_CHARS_PER_SIDE = 500
CORE_MODEL = "gpt-5.4"
TRAJECTORY_MODEL = "gpt-5.4"
CORE_PROMPT_VERSION = "core_eval_v1"
TRAJECTORY_PROMPT_VERSION = "trajectory_eval_v1"
ASYNC_START_DELAY_MS = 30
RECONCILE_SCORE_TOLERANCE = 8
